-- CLEANUP: Drop tables if they exist to start fresh
drop table if exists task_inventory_requests cascade;
drop table if exists finance_transactions cascade;
drop table if exists inventory_transactions cascade;
drop table if exists inventory_items cascade;
drop table if exists messages cascade;
drop table if exists tasks cascade;
drop table if exists events cascade;
drop table if exists weddings cascade;
drop table if exists wedding_templates cascade;
drop table if exists vendors cascade;
drop table if exists workers cascade;
drop table if exists profiles cascade;

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text check (role in ('owner', 'lead', 'worker')),
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. WORKERS
create table workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  email text,
  phone text,
  available boolean default true,
  skills text[],
  rating numeric,
  "joinDate" date
);

-- 3. VENDORS (New Table)
create table vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  category text, -- e.g., 'Catering', 'Decor'
  rating numeric,
  status text check (status in ('Confirmed', 'Pending', 'Rejected')),
  phone text,
  email text,
  location text,
  pricing text,
  services text[]
);

-- 4. WEDDINGS (Top-Level Entity)
create table weddings (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g., "Sharma-Patel Wedding"
  "clientName" text not null,
  "brideName" text,
  "groomName" text,
  "weddingType" text, -- e.g., "North Indian Punjabi"
  "totalBudget" numeric default 0,
  "startDate" timestamp with time zone,
  "endDate" timestamp with time zone,
  status text check (status in ('Active', 'Upcoming', 'Completed', 'Cancelled')) default 'Active',
  created_at timestamp with time zone default now()
);

-- 5. EVENTS (Sub-events within a wedding, or standalone)
create table events (
  id bigint generated by default as identity primary key,
  "weddingId" bigint references weddings(id) on delete cascade, -- Nullable for standalone events
  name text not null, 
  type text, 
  dates text, -- e.g. "Dec 13" or specific date string
  "startDate" timestamp with time zone, -- Formal date for sorting/logic
  "startTime" time,
  "endTime" time,
  status text check (status in ('Active', 'Upcoming', 'Completed')),
  location text,
  venue text,
  "venueAddress" text,
  budget numeric default 0,
  spent numeric default 0,
  progress integer default 0,
  description text,
  "primaryLeadId" bigint references workers(id),
  "departmentLeads" jsonb, -- Array of {id, category, leadId, leadName}
  attendance integer,
  workers bigint[] -- Array of worker IDs
);

-- 6. TASKS
create table tasks (
  id bigint generated by default as identity primary key,
  "weddingId" bigint references weddings(id) on delete cascade,
  "eventId" bigint references events(id) on delete cascade,
  title text not null,
  description text,
  status text check (status in ('Open', 'In Progress', 'Submitted', 'Approved', 'Completed', 'Blocked')),
  priority text check (priority in ('High', 'Medium', 'Normal')),
  "dueDate" text,
  assignee bigint references workers(id),
  budget numeric,
  spent numeric,
  "submittedBy" bigint references workers(id),
  department text,
  "vendorId" bigint references vendors(id),
  "requiresOwnerApproval" boolean default false,
  "approverId" bigint references workers(id), /* or profiles(id) */
  "rejectionNote" text,
  "helpNote" text,
  "checklistDone" integer default 0,
  "checklistTotal" integer default 0,
  checklist jsonb -- Array of {text, completed}
);

-- 7. MESSAGES (New for Chat)
create table messages (
  id bigint generated by default as identity primary key,
  "weddingId" bigint references weddings(id) on delete cascade,
  "eventId" bigint references events(id) on delete cascade,
  "senderId" text, -- 'me', 'sys', or worker ID (for now keeping flexible)
  text text,
  "isSystem" boolean default false,
  timestamp timestamp with time zone default now()
);

-- 8. WEDDING TEMPLATES
create table wedding_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  default_events jsonb -- List of events with {name, type, budget_share, defaultTasks...}
);

-- 9. INVENTORY & FINANCE
create table inventory_items (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  category text,
  "totalQuantity" integer default 0,
  "availableQuantity" integer default 0,
  "pricePerUnit" numeric default 0,
  "imageUrl" text,
  description text
);

create table inventory_transactions (
  id uuid default uuid_generate_v4() primary key,
  "itemId" uuid references inventory_items(id),
  "eventId" bigint references events(id),
  "taskId" bigint references tasks(id),
  type text check (type in ('Check-In', 'Check-Out', 'Maintenance', 'Purchase', 'Loss')),
  quantity integer not null,
  timestamp timestamp with time zone default now(),
  notes text,
  "performedBy" uuid references auth.users(id)
);

create table finance_transactions (
  id uuid default uuid_generate_v4() primary key,
  "eventId" bigint references events(id),
  type text check (type in ('Income', 'Expense')),
  category text,
  amount numeric not null,
  mode text,
  status text check (status in ('Paid', 'Pending', 'Overdue')),
  date timestamp with time zone default now(),
  notes text,
  "recordedBy" uuid references auth.users(id)
);

create table task_inventory_requests (
  id uuid default uuid_generate_v4() primary key,
  "taskId" bigint references tasks(id),
  "itemId" uuid references inventory_items(id),
  quantity integer not null,
  status text check (status in ('Requested', 'Approved', 'Rejected', 'Used', 'Returned')),
  "requestedBy" uuid references auth.users(id),
  "approvedBy" uuid references auth.users(id),
  createdAt timestamp with time zone default now()
);


-- RLS Policies
alter table profiles enable row level security;
alter table weddings enable row level security;
alter table events enable row level security;
alter table tasks enable row level security;
alter table workers enable row level security;
alter table vendors enable row level security;
alter table messages enable row level security;
alter table wedding_templates enable row level security;
alter table inventory_items enable row level security;
alter table inventory_transactions enable row level security;
alter table finance_transactions enable row level security;
alter table task_inventory_requests enable row level security;

create policy "Public access" on profiles for all using (true);
create policy "Public access" on weddings for all using (true);
create policy "Public access" on events for all using (true);
create policy "Public access" on tasks for all using (true);
create policy "Public access" on workers for all using (true);
create policy "Public access" on vendors for all using (true);
create policy "Public access" on messages for all using (true);
create policy "Public access" on wedding_templates for all using (true);
create policy "Public access" on inventory_items for all using (true);
create policy "Public access" on inventory_transactions for all using (true);
create policy "Public access" on finance_transactions for all using (true);
create policy "Public access" on task_inventory_requests for all using (true);


-- SEED DATA ------------------------------------------

-- 1. Workers
insert into workers (name, role, email, phone, skills, rating, available, "joinDate") values
('Rajesh Kumar', 'Logistics Lead', 'rajesh@eventpro.com', '919876543210', ARRAY['Logistics', 'Transport'], 4.8, true, '2024-01-15'),
('Priya Singh', 'Design Lead', 'priya@eventpro.com', '919876543211', ARRAY['Decor', 'Lighting'], 4.9, true, '2024-03-20'),
('Amit Patel', 'General Worker', 'amit@eventpro.com', '919876543212', ARRAY['Setup', 'Moving'], 4.5, true, '2024-08-15');

-- 2. Vendors
insert into vendors (name, category, rating, status, phone, location) values
('Royal Caterers', 'Catering', 4.5, 'Confirmed', '+91 98765 00001', 'South Delhi'),
('Light Magic', 'Lighting', 4.8, 'Pending', '+91 98765 00002', 'Noida'),
('Bloom Florists', 'Decor', 4.6, 'Confirmed', '+91 98765 00003', 'Gurgaon');

-- 3. Templates (Synced with JS)
insert into wedding_templates (name, description, default_events) values
('Punjabi Hindu Wedding', 'The quintessential "Big Fat Delhi Wedding." High energy, grand scale, and extensive festivities.', 
  '[
    {"name": "Roka Ceremony", "type": "Pre-Wedding", "description": "Formal acceptance of marriage proposal.", "budget_share": 0.03, "day_offset": -90, "defaultTasks": [
        {"title": "Book photographer", "subtasks": [], "due_date_offset": -30},
        {"title": "Finalize guest list", "subtasks": [], "due_date_offset": -15},
        {"title": "Order mithai/snacks", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange shagun items", "subtasks": ["Tilak", "Dried fruits", "Clothes"], "due_date_offset": -5},
        {"title": "Coordinate family schedules", "subtasks": [], "due_date_offset": -14}
    ]},
    {"name": "Kurmai/Sagai (Engagement)", "type": "Pre-Wedding", "description": "Ring exchange and Chunni ceremony.", "budget_share": 0.08, "day_offset": -45, "defaultTasks": [
        {"title": "Book venue", "subtasks": [], "due_date_offset": -90},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -60},
        {"title": "Book decorator", "subtasks": [], "due_date_offset": -45},
        {"title": "Order engagement rings", "subtasks": [], "due_date_offset": -45},
        {"title": "Design invitations", "subtasks": [], "due_date_offset": -30},
        {"title": "Book DJ/music", "subtasks": [], "due_date_offset": -30},
        {"title": "Finalize menu", "subtasks": [], "due_date_offset": -21},
        {"title": "Confirm priest availability", "subtasks": [], "due_date_offset": -14},
        {"title": "Arrange gift trays/platters", "subtasks": [], "due_date_offset": -7},
        {"title": "Day-before setup coordination", "subtasks": [], "due_date_offset": -1},
        {"title": "Day-of vendor arrival coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Sangeet Night", "type": "Pre-Wedding", "description": "Grand musical night with dance performances.", "budget_share": 0.12, "day_offset": -2, "defaultTasks": [
        {"title": "Book venue", "subtasks": [], "due_date_offset": -180},
        {"title": "Book choreographer", "subtasks": [], "due_date_offset": -90},
        {"title": "Start dance rehearsals", "subtasks": [], "due_date_offset": -60},
        {"title": "Book DJ/band", "subtasks": [], "due_date_offset": -90},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Finalize song list", "subtasks": [], "due_date_offset": -30},
        {"title": "Finalize menu", "subtasks": [], "due_date_offset": -21},
        {"title": "Arrange stage/backdrop", "subtasks": [], "due_date_offset": -14},
        {"title": "Coordinate lighting", "subtasks": [], "due_date_offset": -7},
        {"title": "Final rehearsal", "subtasks": [], "due_date_offset": -2},
        {"title": "Setup supervision", "subtasks": [], "due_date_offset": 0},
        {"title": "Sound check", "subtasks": [], "due_date_offset": 0},
        {"title": "Performance coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Mehndi Ceremony", "type": "Pre-Wedding", "description": "Henna application for bride and guests.", "budget_share": 0.05, "day_offset": -1, "defaultTasks": [
        {"title": "Book mehndi artists", "subtasks": ["3-5 for bride", "2-3 for guests"], "due_date_offset": -60},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Order decorations", "subtasks": ["Marigold flowers", "Yellow drapes"], "due_date_offset": -30},
        {"title": "Arrange seating", "subtasks": ["Low seats", "Cushions"], "due_date_offset": -7},
        {"title": "Confirm mehndi artist timing", "subtasks": [], "due_date_offset": -3},
        {"title": "Setup venue decorations", "subtasks": [], "due_date_offset": -1},
        {"title": "Arrange refreshments for artists", "subtasks": [], "due_date_offset": 0},
        {"title": "Coordinate artist schedules", "subtasks": [], "due_date_offset": 0},
        {"title": "Photography coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Jaggo/Jago Ceremony", "type": "Pre-Wedding", "description": "Lively procession with decorated copper pots.", "budget_share": 0.02, "day_offset": -1, "defaultTasks": [
        {"title": "Book dhol players", "subtasks": [], "due_date_offset": -60},
        {"title": "Prepare decorated pots (gaggar)", "subtasks": ["Diyas", "Oil"], "due_date_offset": -3},
        {"title": "Coordinate route through neighborhood", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange safety/security", "subtasks": [], "due_date_offset": -2},
        {"title": "Evening coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Haldi/Maiyan Ceremony", "type": "Pre-Wedding", "description": "Turmeric paste application ritual.", "budget_share": 0.03, "day_offset": 0, "defaultTasks": [
        {"title": "Prepare haldi paste", "subtasks": [], "due_date_offset": -1},
        {"title": "Arrange flowers", "subtasks": ["Marigolds"], "due_date_offset": -1},
        {"title": "Setup decorations", "subtasks": [], "due_date_offset": 0},
        {"title": "Coordinate family members", "subtasks": [], "due_date_offset": 0},
        {"title": "Photography setup", "subtasks": [], "due_date_offset": 0},
        {"title": "Cleanup arrangements", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Chooda/Chura Ceremony", "type": "Pre-Wedding", "description": "Bangle ceremony by maternal uncle.", "budget_share": 0.02, "day_offset": 0, "defaultTasks": [
        {"title": "Purchase chooda", "subtasks": ["Red & white bangles"], "due_date_offset": -30},
        {"title": "Purchase kalire", "subtasks": [], "due_date_offset": -15},
        {"title": "Coordinate mama/mami arrival", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange morning breakfast", "subtasks": [], "due_date_offset": -1},
        {"title": "Photography coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Wedding Day", "type": "Wedding", "description": "Baraat, Milni, Varmala, and Pheras.", "budget_share": 0.35, "day_offset": 0, "defaultTasks": [
        {"title": "Final venue walkthrough", "subtasks": [], "due_date_offset": -7},
        {"title": "Confirm all vendor timings", "subtasks": [], "due_date_offset": -3},
        {"title": "Arrange baraat vehicle", "subtasks": ["Horse", "Vintage car"], "due_date_offset": -30},
        {"title": "Book band for baraat", "subtasks": [], "due_date_offset": -90},
        {"title": "Finalize mandap design", "subtasks": [], "due_date_offset": -30},
        {"title": "Coordinate priest for muhurat", "subtasks": [], "due_date_offset": -60},
        {"title": "Finalize menu", "subtasks": [], "due_date_offset": -21},
        {"title": "Arrange wedding outfit", "subtasks": [], "due_date_offset": -120},
        {"title": "Book makeup artist", "subtasks": [], "due_date_offset": -120},
        {"title": "Guest accommodation arrangements", "subtasks": [], "due_date_offset": -60},
        {"title": "Setup begins", "subtasks": [], "due_date_offset": 0},
        {"title": "Decorator setup oversight", "subtasks": [], "due_date_offset": 0},
        {"title": "Caterer arrival & setup", "subtasks": [], "due_date_offset": 0},
        {"title": "Sound & lighting check", "subtasks": [], "due_date_offset": 0},
        {"title": "Bridal makeup begins", "subtasks": [], "due_date_offset": 0},
        {"title": "Baraat departure coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Milni ceremony coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Varmala stage management", "subtasks": [], "due_date_offset": 0},
        {"title": "Phera ceremony coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Dinner service oversight", "subtasks": [], "due_date_offset": 0},
        {"title": "Bidai ceremony coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Reception", "type": "Post-Wedding", "description": "Formal party for extended social circle.", "budget_share": 0.18, "day_offset": 1, "defaultTasks": [
        {"title": "Book venue", "subtasks": [], "due_date_offset": -270},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -180},
        {"title": "Book decorator", "subtasks": [], "due_date_offset": -120},
        {"title": "Design stage/backdrop", "subtasks": [], "due_date_offset": -60},
        {"title": "Order reception outfits", "subtasks": [], "due_date_offset": -120},
        {"title": "Plan couple''s entry choreography", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange cake", "subtasks": [], "due_date_offset": -15},
        {"title": "Coordinate bar setup", "subtasks": [], "due_date_offset": -7},
        {"title": "Finalize music playlist", "subtasks": [], "due_date_offset": -14},
        {"title": "Setup coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Sound check", "subtasks": [], "due_date_offset": 0},
        {"title": "Couple''s entry coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Cake cutting coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Photography direction", "subtasks": [], "due_date_offset": 0},
        {"title": "Dinner service oversight", "subtasks": [], "due_date_offset": 0}
    ]}
   ]'
),
('Marwari/Baniya Wedding', 'Traditional and opulent, often with high jewelry spend and specific rituals like Myra.', 
  '[
    {"name": "Raatri Jaga", "type": "Pre-Wedding", "description": "Ongoing ritual with swastika painting and family songs.", "budget_share": 0.01, "day_offset": -7, "defaultTasks": [
        {"title": "Arrange priest for initial ceremony", "subtasks": [], "due_date_offset": -7},
        {"title": "Purchase sacred symbols materials", "subtasks": [], "due_date_offset": -10},
        {"title": "Coordinate between both homes", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Ganpati Sthapana", "type": "Pre-Wedding", "description": "Installation of Lord Ganesh idol.", "budget_share": 0.01, "day_offset": -5, "defaultTasks": [
        {"title": "Arrange Vinayak boy", "subtasks": [], "due_date_offset": -7},
        {"title": "Purchase Ganpati idol", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange puja materials", "subtasks": [], "due_date_offset": -3},
        {"title": "Coordinate priest", "subtasks": [], "due_date_offset": -5}
    ]},
    {"name": "Bhaat Nyotana", "type": "Pre-Wedding", "description": "Formal invitation to maternal family.", "budget_share": 0.01, "day_offset": -4, "defaultTasks": [
        {"title": "Prepare invitation packets", "subtasks": [], "due_date_offset": -7},
        {"title": "Coordinate with maternal family", "subtasks": [], "due_date_offset": -14},
        {"title": "Arrange refreshments", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Mahira Dastoor (Bhaat)", "type": "Pre-Wedding", "description": "Maternal uncle brings gifts for the family.", "budget_share": 0.05, "day_offset": -3, "defaultTasks": [
        {"title": "Coordinate with mama", "subtasks": [], "due_date_offset": -60},
        {"title": "Arrange gift display area", "subtasks": [], "due_date_offset": -7},
        {"title": "Organize formal ceremony", "subtasks": [], "due_date_offset": -3}
    ]},
    {"name": "Palla Dastoor", "type": "Pre-Wedding", "description": "Bridal outfit formally displayed and blessed.", "budget_share": 0.02, "day_offset": -2, "defaultTasks": [
        {"title": "Prepare bridal outfit for display", "subtasks": [], "due_date_offset": -3},
        {"title": "Arrange display setup", "subtasks": [], "due_date_offset": -1},
        {"title": "Coordinate family blessing ceremony", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Pithi/Telbaan", "type": "Pre-Wedding", "description": "Turmeric & oil application with Ghungra sweets.", "budget_share": 0.03, "day_offset": -1, "defaultTasks": [
        {"title": "Prepare haldi/oil mixture", "subtasks": [], "due_date_offset": -2},
        {"title": "Order ghungra sweets", "subtasks": [], "due_date_offset": -3},
        {"title": "Arrange decorations", "subtasks": [], "due_date_offset": -2},
        {"title": "Setup coordination", "subtasks": [], "due_date_offset": -1}
    ]},
    {"name": "Sangeet & Mehendi", "type": "Pre-Wedding", "description": "Combined grand celebration.", "budget_share": 0.15, "day_offset": -1, "defaultTasks": [
        {"title": "Book Choreographer", "subtasks": [], "due_date_offset": -90},
        {"title": "Book DJ/Band", "subtasks": [], "due_date_offset": -90},
        {"title": "Book Mehndi artists", "subtasks": [], "due_date_offset": -60},
        {"title": "Book Caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Book Decorator", "subtasks": [], "due_date_offset": -90},
        {"title": "Book Photographer", "subtasks": [], "due_date_offset": -120},
        {"title": "Stage Setup", "subtasks": [], "due_date_offset": -14},
        {"title": "Lighting Coordination", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Thamb Puja", "type": "Pre-Wedding", "description": "Worship of the ceremonial pillar at entrance.", "budget_share": 0.01, "day_offset": 0, "defaultTasks": [
        {"title": "Arrange ceremonial pillar", "subtasks": [], "due_date_offset": -7},
        {"title": "Decorate pillar", "subtasks": [], "due_date_offset": -1},
        {"title": "Coordinate priest for specific mantras", "subtasks": [], "due_date_offset": -3}
    ]},
    {"name": "Wedding Ceremony", "type": "Wedding", "description": "Grand wedding with Havan (11 Brahmins).", "budget_share": 0.40, "day_offset": 0, "defaultTasks": [
        {"title": "Confirm availability of 11 Brahmins", "subtasks": [], "due_date_offset": -60},
        {"title": "Arrange aanjhala (jeweled money bag)", "subtasks": [], "due_date_offset": -30},
        {"title": "Book Venue", "subtasks": [], "due_date_offset": -180},
        {"title": "Book Caterer (Vegetarian)", "subtasks": [], "due_date_offset": -180},
        {"title": "Book Decorator", "subtasks": [], "due_date_offset": -120},
        {"title": "Book Photographer/Videographer", "subtasks": [], "due_date_offset": -120},
        {"title": "Book DJ/Lighting", "subtasks": [], "due_date_offset": -90},
        {"title": "Baraat coordination", "subtasks": [], "due_date_offset": 0},
        {"title": "Havan Samagri", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Reception", "type": "Post-Wedding", "description": "Grand post-wedding celebration.", "budget_share": 0.20, "day_offset": 1, "defaultTasks": [
        {"title": "Book venue", "subtasks": [], "due_date_offset": -270},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -180},
        {"title": "Book decorator", "subtasks": [], "due_date_offset": -120},
        {"title": "Design stage/backdrop", "subtasks": [], "due_date_offset": -60},
        {"title": "Order reception outfits", "subtasks": [], "due_date_offset": -120},
        {"title": "Plan couple''s entry", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange cake", "subtasks": [], "due_date_offset": -14},
        {"title": "Bar setup", "subtasks": [], "due_date_offset": -7},
        {"title": "Finalize music", "subtasks": [], "due_date_offset": -14},
        {"title": "Guest management", "subtasks": [], "due_date_offset": 0}
    ]}
   ]'
),
('Jain Wedding', 'Values-driven celebration with strict Sattvic food and specific 4-phera ritual.', 
  '[
    {"name": "Gol Dhana (Engagement)", "type": "Pre-Wedding", "description": "Exchange of coriander seeds (dhana) and jaggery (gol).", "budget_share": 0.08, "day_offset": -60, "defaultTasks": [
        {"title": "Book venue with Sattvic kitchen", "subtasks": [], "due_date_offset": -180},
        {"title": "Verify caterer''s Jain credentials", "subtasks": [], "due_date_offset": -120},
        {"title": "Arrange coriander-jaggery packets", "subtasks": [], "due_date_offset": -30},
        {"title": "Confirm Jain Pandit availability", "subtasks": [], "due_date_offset": -60},
        {"title": "Book photographer", "subtasks": [], "due_date_offset": -120},
        {"title": "Finalize strictly Jain menu", "subtasks": [], "due_date_offset": -45}
    ]},
    {"name": "Lagana Lekhan", "type": "Pre-Wedding", "description": "Written commitment of marriage.", "budget_share": 0.02, "day_offset": -30, "defaultTasks": [
        {"title": "Prepare formal documents", "subtasks": [], "due_date_offset": -30},
        {"title": "Coordinate witness attendance", "subtasks": [], "due_date_offset": -14},
        {"title": "Arrange temple/home ceremony", "subtasks": [], "due_date_offset": -21}
    ]},
    {"name": "Mandap Mahurat", "type": "Pre-Wedding", "description": "Auspicious mandap installation.", "budget_share": 0.02, "day_offset": -3, "defaultTasks": [
        {"title": "Confirm muhurat timing with Jain astrologer", "subtasks": [], "due_date_offset": -60},
        {"title": "Coordinate mandap designer", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange installation materials", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Pithi (Haldi)", "type": "Pre-Wedding", "description": "Turmeric paste application.", "budget_share": 0.03, "day_offset": -2, "defaultTasks": [
        {"title": "Prepare turmeric paste", "subtasks": [], "due_date_offset": -2},
        {"title": "Arrange decorations", "subtasks": [], "due_date_offset": -3},
        {"title": "Confirm Sattvic catering", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Mehendi", "type": "Pre-Wedding", "description": "Henna ceremony.", "budget_share": 0.04, "day_offset": -1, "defaultTasks": [
        {"title": "Book Mehendi artists", "subtasks": [], "due_date_offset": -60},
        {"title": "Verify Sattvic refreshments", "subtasks": [], "due_date_offset": -14},
        {"title": "Decor", "subtasks": [], "due_date_offset": -30}
    ]},
    {"name": "Sangeet", "type": "Pre-Wedding", "description": "Musical celebration.", "budget_share": 0.12, "day_offset": -1, "defaultTasks": [
        {"title": "Book DJ/Band", "subtasks": [], "due_date_offset": -90},
        {"title": "Book Sattvic Caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Book Decorator", "subtasks": [], "due_date_offset": -90},
        {"title": "Book Choreographer", "subtasks": [], "due_date_offset": -60},
        {"title": "Verification of no root vegetables in menu", "subtasks": [], "due_date_offset": -21}
    ]},
    {"name": "Wedding Ceremony (Vivah)", "type": "Wedding", "description": "Vivah with 4 Pheras.", "budget_share": 0.35, "day_offset": 0, "defaultTasks": [
        {"title": "Confirm Jain Pandit", "subtasks": [], "due_date_offset": -90},
        {"title": "Verify venue has NO onion/garlic in any kitchen", "subtasks": [], "due_date_offset": -180},
        {"title": "Book caterer specializing in Jain cuisine", "subtasks": [], "due_date_offset": -180},
        {"title": "Arrange Jain religious items", "subtasks": ["Tilak", "Sacred thread"], "due_date_offset": -30},
        {"title": "Madhuparka arrangement", "subtasks": [], "due_date_offset": 0},
        {"title": "Var Puja arrangement", "subtasks": [], "due_date_offset": 0},
        {"title": "4 Pheras setup", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Jina Grahe Dhan Arpana", "type": "Post-Wedding", "description": "Temple visit and donation.", "budget_share": 0.02, "day_offset": 2, "defaultTasks": [
        {"title": "Coordinate temple visit", "subtasks": [], "due_date_offset": -7},
        {"title": "Prepare donation", "subtasks": [], "due_date_offset": -1}
    ]},
    {"name": "Reception", "type": "Post-Wedding", "description": "Formal reception (No Alcohol).", "budget_share": 0.18, "day_offset": 1, "defaultTasks": [
        {"title": "Book Venue", "subtasks": [], "due_date_offset": -270},
        {"title": "Sattvic Catering Verification", "subtasks": [], "due_date_offset": -60},
        {"title": "Decor", "subtasks": [], "due_date_offset": -90},
        {"title": "Photographer", "subtasks": [], "due_date_offset": -120},
        {"title": "Confirm NO alcohol service", "subtasks": [], "due_date_offset": -30}
    ]}
   ]'
),
('Sikh Wedding (Anand Karaj)', 'Centered around the Gurudwara ceremony. Must be held before noon.', 
  '[
    {"name": "Roka Ceremony", "type": "Pre-Wedding", "description": "Formal acceptance.", "budget_share": 0.03, "day_offset": -90, "defaultTasks": [
        {"title": "Book Photographer", "subtasks": [], "due_date_offset": -30},
        {"title": "Finalize guest list", "subtasks": [], "due_date_offset": -15},
        {"title": "Order mithai/snacks", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange shagun items", "subtasks": [], "due_date_offset": -5}
    ]},
    {"name": "Kurmai (Engagement)", "type": "Pre-Wedding", "description": "Engagement ceremony with Kirtan.", "budget_share": 0.08, "day_offset": -60, "defaultTasks": [
        {"title": "Book Gurudwara", "subtasks": [], "due_date_offset": -180},
        {"title": "Book Banquet (Lunch)", "subtasks": [], "due_date_offset": -180},
        {"title": "Arrange Raagi musicians", "subtasks": [], "due_date_offset": -90},
        {"title": "Coordinate Langar arrangements", "subtasks": [], "due_date_offset": -14}
    ]},
    {"name": "Akhand Path", "type": "Pre-Wedding", "description": "48-hour continuous scripture reading.", "budget_share": 0.02, "day_offset": -5, "defaultTasks": [
        {"title": "Arrange Guru Granth Sahib and platform", "subtasks": [], "due_date_offset": -30},
        {"title": "Book Paathis for continuous reading shifts", "subtasks": [], "due_date_offset": -30},
        {"title": "Setup reading area at home/Gurudwara", "subtasks": [], "due_date_offset": -14},
        {"title": "Coordinate family attendance shifts", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange refreshments for Paathis", "subtasks": [], "due_date_offset": -3}
    ]},
    {"name": "Maiyan/Vatna", "type": "Pre-Wedding", "description": "Turmeric application (Haldi).", "budget_share": 0.02, "day_offset": -3, "defaultTasks": [
        {"title": "Prepare ubtan mixture", "subtasks": [], "due_date_offset": -5},
        {"title": "Arrange decorations", "subtasks": [], "due_date_offset": -5},
        {"title": "Coordinate daily ceremonies", "subtasks": [], "due_date_offset": -5}
    ]},
    {"name": "Sangeet", "type": "Pre-Wedding", "description": "Dance and music night.", "budget_share": 0.12, "day_offset": -2, "defaultTasks": [
        {"title": "Book Choreographer", "subtasks": [], "due_date_offset": -90},
        {"title": "Book DJ/Dhol players", "subtasks": [], "due_date_offset": -90},
        {"title": "Book Caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Book Decorator", "subtasks": [], "due_date_offset": -90}
    ]},
    {"name": "Mehendi", "type": "Pre-Wedding", "description": "Henna ceremony.", "budget_share": 0.04, "day_offset": -2, "defaultTasks": [
        {"title": "Book Mehndi artists", "subtasks": [], "due_date_offset": -60},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Decorations", "subtasks": [], "due_date_offset": -30},
        {"title": "Seating arrangements", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Jaggo", "type": "Pre-Wedding", "description": "Lively procession with oil lamps.", "budget_share": 0.04, "day_offset": -1, "defaultTasks": [
        {"title": "Book dhol players", "subtasks": [], "due_date_offset": -60},
        {"title": "Prepare decorated pots (gaggar)", "subtasks": ["Diyas", "Oil"], "due_date_offset": -7},
        {"title": "Plan procession route", "subtasks": [], "due_date_offset": -14},
        {"title": "Coordinate neighborhood permissions", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange safety measures", "subtasks": [], "due_date_offset": -3}
    ]},
    {"name": "Chooda/Churha Ceremony", "type": "Pre-Wedding", "description": "Bangle ceremony by maternal uncle.", "budget_share": 0.02, "day_offset": 0, "defaultTasks": [
        {"title": "Purchase chooda", "subtasks": [], "due_date_offset": -30},
        {"title": "Purchase kalire", "subtasks": [], "due_date_offset": -30},
        {"title": "Coordinate mama/mami arrival", "subtasks": [], "due_date_offset": -7},
        {"title": "Arrange morning meal", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Anand Karaj", "type": "Wedding", "description": "Morning ceremony at Gurudwara.", "budget_share": 0.08, "day_offset": 0, "defaultTasks": [
        {"title": "Book Gurudwara", "subtasks": [], "due_date_offset": -365},
        {"title": "Confirm Raagi musicians", "subtasks": [], "due_date_offset": -90},
        {"title": "Coordinate Langar arrangements", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange Rumala Sahib", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange Palki Sahib", "subtasks": [], "due_date_offset": -30},
        {"title": "Coordinate family seating", "subtasks": [], "due_date_offset": -14},
        {"title": "Confirm Lavaan timing", "subtasks": [], "due_date_offset": -3}
    ]},
    {"name": "Langar", "type": "Wedding", "description": "Community meal served to all.", "budget_share": 0.00, "day_offset": 0, "defaultTasks": [
        {"title": "Coordinate meal arrangements", "subtasks": [], "due_date_offset": -30},
        {"title": "Ensure sufficient quantity", "subtasks": [], "due_date_offset": -7},
        {"title": "Volunteer coordination", "subtasks": [], "due_date_offset": -7}
    ]},
    {"name": "Reception", "type": "Post-Wedding", "description": "Evening party with alcohol permitted.", "budget_share": 0.25, "day_offset": 0, "defaultTasks": [
        {"title": "Book Venue", "subtasks": [], "due_date_offset": -270},
        {"title": "Book Caterer", "subtasks": [], "due_date_offset": -180},
        {"title": "Book Decorator", "subtasks": [], "due_date_offset": -120},
        {"title": "Book DJ/Band", "subtasks": [], "due_date_offset": -120},
        {"title": "Book Photographer", "subtasks": [], "due_date_offset": -120},
        {"title": "Bar service", "subtasks": [], "due_date_offset": -60}
    ]}
   ]'
),
('Sindhi Wedding', 'Fun-filled, dance-heavy, often with late-night Baraat and unique rituals like Saanth.', 
  '[
    {"name": "Berana Satsang", "type": "Pre-Wedding", "description": "Worship of Jhulelal, starting 10-day prayer period.", "budget_share": 0.01, "day_offset": -10, "defaultTasks": [
        {"title": "Arrange Jhulelal idol/image", "subtasks": [], "due_date_offset": -15},
        {"title": "Coordinate priest for initial satsang", "subtasks": [], "due_date_offset": -12},
        {"title": "Setup prayer area", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Pakki (Formal Engagement)", "type": "Pre-Wedding", "description": "Ring exchange and formal engagement.", "budget_share": 0.07, "day_offset": -45, "defaultTasks": [
        {"title": "Book Venue", "subtasks": [], "due_date_offset": -90},
        {"title": "Rings", "subtasks": [], "due_date_offset": -45},
        {"title": "Caterer", "subtasks": [], "due_date_offset": -60},
        {"title": "Music", "subtasks": [], "due_date_offset": -30},
        {"title": "Decorator", "subtasks": [], "due_date_offset": -45}
    ]},
    {"name": "Kacchi Misri", "type": "Pre-Wedding", "description": "Sweetening the relationship with rock sugar.", "budget_share": 0.02, "day_offset": -30, "defaultTasks": [
        {"title": "Purchase special misri", "subtasks": ["Rock sugar"], "due_date_offset": -30},
        {"title": "Arrange silver/decorative plates", "subtasks": [], "due_date_offset": -21},
        {"title": "Coordinate ceremony timing", "subtasks": [], "due_date_offset": -14}
    ]},
    {"name": "Sagri", "type": "Pre-Wedding", "description": "Groom''s family sends gifts to bride.", "budget_share": 0.03, "day_offset": -7, "defaultTasks": [
        {"title": "Coordinate gift selection with groom''s family", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange gift display area", "subtasks": [], "due_date_offset": -14},
        {"title": "Organize formal presentation ceremony", "subtasks": [], "due_date_offset": -10}
    ]},
    {"name": "Mehendi", "type": "Pre-Wedding", "description": "Henna application ceremony.", "budget_share": 0.05, "day_offset": -2, "defaultTasks": [
        {"title": "Book Mehndi artists", "subtasks": [], "due_date_offset": -60},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -120},
        {"title": "Decorations", "subtasks": [], "due_date_offset": -30},
        {"title": "Photographer", "subtasks": [], "due_date_offset": -120}
    ]},
    {"name": "Sangeet", "type": "Pre-Wedding", "description": "Grand competitive dance party.", "budget_share": 0.15, "day_offset": -2, "defaultTasks": [
        {"title": "Book Choreographer (Essential)", "subtasks": [], "due_date_offset": -150},
        {"title": "Extended rehearsal schedule", "subtasks": [], "due_date_offset": -90},
        {"title": "Book DJ and live band", "subtasks": [], "due_date_offset": -120},
        {"title": "Plan elaborate stage design", "subtasks": [], "due_date_offset": -60},
        {"title": "Lighting", "subtasks": [], "due_date_offset": -30}
    ]},
    {"name": "Dev Bithana", "type": "Pre-Wedding", "description": "Installation of Lord Ganesha and Jhulelal.", "budget_share": 0.02, "day_offset": -1, "defaultTasks": [
        {"title": "Arrange idols", "subtasks": [], "due_date_offset": -7},
        {"title": "Coordinate priest", "subtasks": [], "due_date_offset": -14},
        {"title": "Setup worship area", "subtasks": [], "due_date_offset": -2}
    ]},
    {"name": "Saanth", "type": "Pre-Wedding", "description": "Ritualistic tearing of groom''s clothes.", "budget_share": 0.01, "day_offset": 0, "defaultTasks": [
        {"title": "Arrange old clothes for ritual", "subtasks": [], "due_date_offset": -7},
        {"title": "Explain ritual to groom", "subtasks": [], "due_date_offset": -3},
        {"title": "Photography coordination", "subtasks": [], "due_date_offset": 0}
    ]},
    {"name": "Wedding Ceremony", "type": "Wedding", "description": "Late night Pheras and Jhulelal worship.", "budget_share": 0.35, "day_offset": 0, "defaultTasks": [
        {"title": "Book all vendors", "subtasks": ["Venue", "Caterer", "Decorator"], "due_date_offset": -270},
        {"title": "Communicate expected baraat delay", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange Jhulelal worship materials", "subtasks": [], "due_date_offset": -30},
        {"title": "Coordinate thread-measuring ritual items", "subtasks": [], "due_date_offset": -14},
        {"title": "Book Venue", "subtasks": ["Extended Hours"], "due_date_offset": -30},
        {"title": "White Horse for Groom", "subtasks": [], "due_date_offset": -30}
    ]},
    {"name": "Reception", "type": "Post-Wedding", "description": "High energy party.", "budget_share": 0.20, "day_offset": 1, "defaultTasks": [
        {"title": "Book venue", "subtasks": [], "due_date_offset": -270},
        {"title": "Book caterer", "subtasks": [], "due_date_offset": -180},
        {"title": "Book decorator", "subtasks": [], "due_date_offset": -120},
        {"title": "Design stage/backdrop", "subtasks": [], "due_date_offset": -60},
        {"title": "Order reception outfits", "subtasks": [], "due_date_offset": -120},
        {"title": "Plan couple''s entry", "subtasks": [], "due_date_offset": -30},
        {"title": "Arrange cake", "subtasks": [], "due_date_offset": -15},
        {"title": "Coordinate bar setup", "subtasks": [], "due_date_offset": -7},
        {"title": "Finalize music", "subtasks": [], "due_date_offset": -14}
    ]}
   ]'
);

-- 4. Sample Wedding
insert into weddings (name, "clientName", "brideName", "groomName", "weddingType", "totalBudget", "startDate", "endDate", status) values
('Sharma-Patel Wedding', 'Sharma Family', 'Priya Sharma', 'Rohan Patel', 'North Indian Punjabi', 5000000, '2025-12-13', '2025-12-16', 'Active');

-- 5. Sample Sub-Events
insert into events ("weddingId", name, type, dates, "startDate", status, location, budget, spent, progress, "primaryLeadId") values
(1, 'Mehndi Ceremony', 'Mehndi', 'Dec 13', '2025-12-13 14:00:00+00', 'Completed', 'Sharma Residence', 500000, 480000, 80, 2),
(1, 'Sangeet Night', 'Sangeet', 'Dec 14', '2025-12-14 19:00:00+00', 'Active', 'Hotel Taj', 1500000, 900000, 60, 1),
(1, 'Wedding Ceremony', 'Wedding', 'Dec 15 PM', '2025-12-15 18:00:00+00', 'Upcoming', 'Grand Palace', 2000000, 700000, 35, 1);

-- 6. Standalone Event
insert into events (name, type, dates, "startDate", status, location, budget, spent, progress, "primaryLeadId") values
('Tech Summit 2024', 'Corporate', 'Nov 15', '2024-11-15 09:00:00+00', 'Active', 'Bangalore Conv Ctr', 1800000, 630000, 35, 1);

-- 7. Sample Tasks
insert into tasks ("weddingId", "eventId", title, status, priority, "dueDate", assignee, budget, "checklistTotal", "checklistDone") values
(1, 2, 'Finalize Sangeet Playlist', 'In Progress', 'High', '2025-12-10', 1, 0, 0, 0),
(1, 2, 'Stage Decor Review', 'Open', 'Medium', '2025-12-12', 2, 500000, 4, 1),
(1, 3, 'Mandap Flower Arrangement', 'Open', 'High', '2025-12-14', 2, 200000, 5, 2);

-- 8. Sample Messages (Chat)
insert into messages ("weddingId", "eventId", "senderId", text, "isSystem") values
(1, 2, 'sys', 'Event created by Sharma Family', true),
(1, 2, 'me', 'Lets coordinate the floral arrangements here.', false);
