-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text check (role in ('owner', 'lead', 'worker')),
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. WORKERS (Matches your mock workers)
create table workers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  email text,
  phone text,
  available boolean default true,
  skills text[], -- Array of strings
  rating numeric
);

-- 3. EVENTS
create table events (
  id bigint generated by default as identity primary key,
  name text not null,
  client text not null,
  dates text, -- Storing as string "Oct 24 - Oct 26" for simplicity, or use daterange
  status text check (status in ('Active', 'Upcoming', 'Completed')),
  location text,
  budget numeric,
  spent numeric,
  progress integer default 0,
  description text,
  "primaryLeadId" bigint references workers(id), -- Quoted because camelCase in frontend
  "departmentLeads" jsonb, -- Storing complex nested objects as JSON for flexibility
  attendance integer,
  workers bigint[] -- Array of worker IDs
);

-- 4. TASKS
create table tasks (
  id bigint generated by default as identity primary key,
  "eventId" bigint references events(id),
  title text not null,
  description text,
  status text check (status in ('Open', 'In Progress', 'Submitted', 'Approved', 'Completed', 'Blocked')),
  priority text check (priority in ('High', 'Medium', 'Normal')),
  "dueDate" text,
  assignee bigint references workers(id),
  budget numeric,
  spent numeric,
  "submittedBy" bigint references workers(id)
);

-- Insert Mock Data (So you don't start empty)
-- Workers
insert into workers (name, role, email, skills, rating, available) values
('Rajesh Kumar', 'Logistics Lead', 'rajesh@eventpro.com', ARRAY['Logistics', 'Transport'], 4.8, true),
('Priya Singh', 'Design Lead', 'priya@eventpro.com', ARRAY['Decor', 'Lighting'], 4.9, true),
('Amit Patel', 'General Worker', 'amit@eventpro.com', ARRAY['Setup', 'Moving'], 4.5, true);

-- Events
insert into events (name, client, dates, status, location, budget, spent, progress, "primaryLeadId") values
('Sharma-Patel Wedding', 'Sharma Family', '2024-10-24', 'Active', 'Udaipur Palace', 5000000, 2100000, 45, 1),
('Tech Summit 2024', 'TechFlow Inc', '2024-11-15', 'Upcoming', 'Bangalore Convention Center', 2500000, 500000, 15, 2);

-- Tasks
insert into tasks ("eventId", title, status, priority, "dueDate", assignee, budget) values
(1, 'Finalize Menu with Caterer', 'In Progress', 'High', '2024-10-20', 1, 1500000),
(1, 'Stage Decoration Setup', 'Open', 'Medium', '2024-10-22', 2, 500000);

-- Enable RLS (Security) - policies can be added later, for now allow all for ease of dev
alter table profiles enable row level security;
alter table events enable row level security;
alter table tasks enable row level security;
alter table workers enable row level security;

create policy "Public access for mvp" on profiles for all using (true);
create policy "Public access for mvp" on events for all using (true);
create policy "Public access for mvp" on tasks for all using (true);
create policy "Public access for mvp" on workers for all using (true);
